baseurl: /
markdown: kramdown
highlighter: rouge # or rouge or null
url: http://tiagones.com.br/
paginate_path: "/blog/page:num/"
exclude: [
  "docs",
  "node_modules",
  "*.bat",
  "*.sublime-project",
  "*.sublime-workspace",
  "bower.json",
  "CNAME",
  "gulpfile.js",
  "package.json",
  "README.md"
]
