#-------------------------------
# General Site Settings
title: Tiagones
description: Sei lá 1 / Sei lá 2 / Sei lá 2
email: hey@tiagones.com.br

#-------------------------------
# Contact Section
social:
- {
    name:   'LinkedIn',
    icon:   'linkedin',
    link:   'https://www.linkedin.com/in/tiagones'
  }
- {
    name:   'CodePen',
    icon:   'codepen',
    link:   'https://codepen.io/tiagones/'
  }
- {
    name:   'Github',
    icon:   'github',
    link:   'https://github.com/tiagones/'
  }
- {
    name:   'Dribbble',
    icon:   'dribbble',
    link:   'https://dribbble.com/tiagones'
  }
- {
    name:   'Behance',
    icon:   'behance',
    link:   'https://www.behance.net/tiagones'
  }
